#!/bin/bash
set -e

SQLITE_DB="$HOME/.local/share/order_groceries/meals.db"
H2_DB="$(cd "$(dirname "$0")" && pwd)/data/groceries"
H2_JAR="/home/tomb/.gradle/caches/modules-2/files-2.1/com.h2database/h2/2.4.240/686180ad33981ad943fdc0ab381e619b2c2fdfe5/h2-2.4.240.jar"
TMP_SQL="/tmp/h2_migration_$$.sql"

if [ ! -f "$SQLITE_DB" ]; then
    echo "ERROR: SQLite DB not found at $SQLITE_DB"
    exit 1
fi

if [ ! -f "$H2_JAR" ]; then
    echo "ERROR: H2 JAR not found at $H2_JAR"
    echo "Run './gradlew dependencies' first to download it."
    exit 1
fi

echo "Exporting from SQLite: $SQLITE_DB"

cat > "$TMP_SQL" << 'ENDSQL'
CREATE TABLE IF NOT EXISTS meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    quantity VARCHAR(255),
    kroger_product_id VARCHAR(255),
    kroger_product_name VARCHAR(255),
    CONSTRAINT uq_ingredient_meal_name UNIQUE (meal_id, name),
    FOREIGN KEY (meal_id) REFERENCES meals(id)
);
ENDSQL

sqlite3 "$SQLITE_DB" \
  "SELECT 'INSERT INTO meals (id, name) VALUES (' || id || ', ' || quote(name) || ');' FROM meals ORDER BY id;" \
  >> "$TMP_SQL"

MEAL_COUNT=$(sqlite3 "$SQLITE_DB" "SELECT COUNT(*) FROM meals;")

sqlite3 "$SQLITE_DB" \
  "SELECT 'INSERT INTO ingredients (id, meal_id, name, quantity, kroger_product_id, kroger_product_name) VALUES (' || id || ', ' || meal_id || ', ' || quote(name) || ', ' || quote(quantity) || ', ' || quote(kroger_product_id) || ', ' || quote(kroger_product_name) || ');' FROM ingredients ORDER BY id;" \
  >> "$TMP_SQL"

INGREDIENT_COUNT=$(sqlite3 "$SQLITE_DB" "SELECT COUNT(*) FROM ingredients;")

echo "Deleting existing H2 database files..."
rm -f "${H2_DB}.mv.db" "${H2_DB}.trace.db"
mkdir -p "$(dirname "$H2_DB")"

echo "Importing into H2..."
java -cp "$H2_JAR" org.h2.tools.RunScript \
    -url "jdbc:h2:file:${H2_DB}" \
    -user sa \
    -password "" \
    -script "$TMP_SQL"

rm -f "$TMP_SQL"
echo "Done. Imported $MEAL_COUNT meals and $INGREDIENT_COUNT ingredients."
